exports.PRODUCT_TARGET_PATH_TYPE_OPTIONS = [{value:'PATH_ONLY',desc:'Path Only'},
                                {value:'YYYYMM',desc:'path/YYYYMM'},
                                {value:'YYYY/MM',desc:'path/YYYY/MM'},
                                {value:'YYYY/MM/DD',desc:'path/YYYY/MM/DD'}];
exports.PRODUCT_SCHEDULE_TYPE = [{value:'EVERY_DAY',desc:'EVERY DAY'},
                            {value:'EVERY_HOUR',desc:'EVERY HOUR'},
                            {value:'EVERY_MIN',desc:'EVERY MIN'}];
exports.PRODUCT_FILTER_TYPE = [{value:'SIMPLE',desc:'SIMPLE'},
                          {value:'REGEXP',desc:'정규표현식(REGEXP)'}];
exports.PRODUCT_PROCESS_TYPE = [{value:'DB_FTP',desc:'Insert DB and Send FTP'},
                            {value:'DB_ONLY',desc:'DB Only'},
                            {value:'FTP_ONLY',desc:'FTP Only'},
                            {value:'REMOVE_LOCAL_ONLY',desc:'Remove local files Only'}];
exports.PRODUCT_DATA_TYPE = [{value:'NULL',desc:'NULL'},
                          {value:'S',desc:'수신영상(기하보정X)'},
                          {value:'SG',desc:'수신영상'},
                          {value:'DG',desc:'1일영상'},
                          {value:'PG',desc:'5일영상'},
                          {value:'WG',desc:'7일영상'},
                          {value:'MG',desc:'계절영상'},
                          {value:'AG',desc:'년영상'}];
exports.PRODUCT_DATA_FORMAT = [{value:'GeoTIFF',desc:'Geo TIFF'},
                            {value:'HDF4',desc:'HDF4'},
                            {value:'HDF5',desc:'HDF5'},
                            {value:'NetCDF',desc:'NetCDF'},
                            {value:'JPG',desc:'JPG'},
                            {value:'PNG',desc:'PNG'},
                            {value:'GIF',desc:'GIF'},
                            {value:'BMP',desc:'BMP'},
                            {value:'BINARY',desc:'BINARY'},
                            {value:'ASCII(PLAIN)',desc:'ASCII(PLAIN)'},
                            {value:'ASCII(XYZ)',desc:'ASCII(XYZ)'},
                            {value:'PASS',desc:'PASS'}];
exports.DATA_GBN_OPTIONS = [{value:'NO-L32',desc:'NOAA CF SST 산출물'},
                            {value:'NO-L31',desc:'NOAA SST 산출물'},
                            {value:'NO-L00',desc:'NOAA PASS'},
                            {value:'MO-L31',desc:'MODIS 산출물'},
                            {value:'MP-L00',desc:'MODIS PASS'},
                            {value:'NP-L31',desc:'NPP L2 산출물'},
                            {value:'NP-L32',desc:'NPP L3 산출물'},
                            {value:'NP-L00',desc:'NPP PASS'},
                            {value:'GO-L10',desc:'GOCI L1 산출물(he5)'},
                            {value:'GO-L20',desc:'GOCI L2 산출물(he5)'},
                            {value:'GO-L30',desc:'GOCI L3 산출물(he5)'},
                            {value:'SW-L00',desc:'SEAWIFS PASS'},
                            {value:'SW-L10',desc:'SEAWIFS L1 산출물'},
                            {value:'SW-L20',desc:'SEAWIFS L2 산출물'},
                            {value:'SW-L30',desc:'SEAWIFS L3 산출물'}];
exports.DATA_AN_GBN_OPTIONS = [{value:'ANGSTROM_531',desc:'ANGSTROM_531'},
                              {value:'CH32',desc:'CH32'},
                              {value:'CHLOR_A',desc:'CHLOR A'},
                              {value:'DAAC_SST',desc:'DAAC SST'},
                              {value:'DAAC_SST4',desc:'DAAC SST4'},
                              {value:'EPS_78',desc:'EPS 78'},
                              {value:'EVI',desc:'EVI'},
                              {value:'K_490',desc:'K_490'},
                              {value:'NDVI',desc:'NDVI'},
                              {value:'NOAA-SST',desc:'NOAA-SST'},
                              {value:'NOAA_CF_SST',desc:'NOAA CF SST'},
                              {value:'PAR',desc:'PAR'},
                              {value:'PASS',desc:'PASS'},
                              {value:'RGB',desc:'RGB'},
                              {value:'RRS_412',desc:'RRS 412'},
                              {value:'RRS_443',desc:'RRS 443'},
                              {value:'RRS_488',desc:'RRS 488'},
                              {value:'RRS_531',desc:'RRS 531'},
                              {value:'RRS_551',desc:'RRS 551'},
                              {value:'RRS_667',desc:'RRS 667'},
                              {value:'RRS_678',desc:'RRS 678'},
                              {value:'RRS_748',desc:'RRS 748'},
                              {value:'RRS_869',desc:'RRS 869'},
                              {value:'SEADAS_SST',desc:'SEADAS SST'},
                              {value:'SEADAS_SST4',desc:'SEADAS SST4'},
                              {value:'TAU_869',desc:'TAU 869'},
                              {value:'nLw_412',desc:'nLw 412'},
                              {value:'nLw_443',desc:'nLw 443'},
                              {value:'nLw_488',desc:'nLw 488'},
                              {value:'nLw_531',desc:'nLw 531'},
                              {value:'nLw_551',desc:'nLw 551'},
                              {value:'nLw_667',desc:'nLw 667'},
                              {value:'nLw_678',desc:'nLw 551'},
                              {value:'nLw_748',desc:'nLw 667'},
                              {value:'nLw_869',desc:'nLw 869'},
                              {value:'LST',desc:'LST'},
                              {value:'SEADAS_CHL',desc:'SEADAS CHL'}];
